#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = [
#   "polib",
#   "langconv"
# ]
# ///

import os
import polib
from langconv.converter import LanguageConverter
from langconv.language.zh import zh_cn

TW_TO_CN = {
    # Computer words
    "搜尋": "搜索",
    "使用者": "用户",
    "載入": "加载",
    "設定": "设置",
    "登入": "登录",
    "套用": "应用",
    "資訊": "信息",
}

for k, v in TW_TO_CN.items():
    zh_cn.rules.insert(k, v)

lc_cn = LanguageConverter.from_language(zh_cn)

with open("app/locales/zh-Hant/messages.po", "r") as f:
    po = polib.pofile(f.read())


GENERATOR = os.path.basename(__file__)
po.metadata["X-Generator"] = GENERATOR
po.metadata["Language"] = "zh-Hans"

for entry in po:
    entry.msgstr = lc_cn.convert(entry.msgstr)

po.header = f"""DO NOT EDIT THIS FILE BY HAND!
REGENERATE THIS FILE USING {GENERATOR}!"""

with open("app/locales/zh-Hans/messages.po", "w") as f:
    f.write(str(po))
